### ISSUE TITLE
stuck at waiting for TOR

### ISSUE THREAD

**Issue by aspieln3r** [houssniyh/pwnloris#1]
distro: arch linux
requirements.txt installed
to reproduce, run
./pwnloris.py -t [hostname]

**Comment by h0ussni** [comment]
Hi @aspieln3r,

Do you have tor installed on your machine?

**Comment by aspieln3r** [comment]
@h0ussni  I fixed the issue by running tor as daemon 
I'd suggest adding this to the readme
